objects/Mix__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mixes</relationshipLabel>
        <relationshipName>Mixes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Genre__c</fullName>
        <label>Primary Genre</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Genre__c</fullName>
        <label>Secondary Genre</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Song__c.object
<CustomObject>
    <fields>
        <fullName>Artist__c</fullName>
        <label>Artist</label>
        <length>180</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Genre__c</fullName>
        <label>Genre</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alternative Music</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Blues</fullName>
                </value>
                <value>
                    <fullName>Classical Music</fullName>
                </value>
                <value>
                    <fullName>Country Music</fullName>
                </value>
                <value>
                    <fullName>Dance Music</fullName>
                </value>
                <value>
                    <fullName>Easy Listening</fullName>
                </value>
                <value>
                    <fullName>Hip Hop / Rap</fullName>
                </value>
                <value>
                    <fullName>Indie Pop</fullName>
                </value>
                <value>
                    <fullName>Jazz</fullName>
                </value>
                <value>
                    <fullName>Latin Music</fullName>
                </value>
                <value>
                    <fullName>new Age</fullName>
                </value>
                <value>
                    <fullName>Opera</fullName>
                </value>
                <value>
                    <fullName>Pop (Popular music)</fullName>
                </value>
                <value>
                    <fullName>R&amp;B / Soul</fullName>
                </value>
                <value>
                    <fullName>Reggae</fullName>
                </value>
                <value>
                    <fullName>Rock</fullName>
                </value>
                <value>
                    <fullName>World Music / Beats</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Length_m__c</fullName>
        <label>Length (m)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Track_Count__c</fullName>
        <label>Track Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Track_Licences__c</fullName>
        <label>Track Licences</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Mix__c</fullName>
        <label>Mix</label>
        <referenceTo>Mix__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <label>Track Autonumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TrackTrigger_Test.cls
@isTest
public class TrackTrigger_Test
{
	public static final Integer MIX_COUNT = 25;

	@testSetup static void setup()
	{
		List<Mix__c> mixes = new List<Mix__c>();
		Contact contact = new Contact(LastName = 'testContact');
		insert contact;
		for (Integer i = 0; i < MIX_COUNT; i++)
		{
			mixes.add(new Mix__c(Name = 'test' + i, Customer__c = contact.Id, Primary_Genre__c = null,
					Secondary_Genre__c = null));
		}
		insert mixes;
		List<sObject> ls = Test.loadData(Song__c.sObjectType, 'songsResourse');
	}

	@isTest
	static void testDelete_changesTrackCountAndGenres()
	{
		Mix__c mix = [select id,Primary_Genre__c, Secondary_Genre__c from Mix__c].get(0);
		List<Song__c> allSongs = [select id, Genre__c, Track_Licences__c,
				(select id From Song__c.Tracks__r) from Song__c];
		List<Track__c> tracks = new List<Track__c>();
		for (Song__c s: allSongs)
		{
			for (Integer i = 0; i < s.Track_Licences__c; i++)
			{
				tracks.add(new Track__c(Mix__c = mix.id, Song__c = s.id));
			}
		}
		insert tracks;

		Test.startTest();
		delete tracks;
		Test.stopTest();

		mix = [select Id, Primary_Genre__c, Secondary_Genre__c from Mix__c where Id=:mix.Id];
		System.assertEquals(null, mix.Primary_Genre__c);
		System.assertEquals(null, mix.Secondary_Genre__c);
		for (Song__c s: [select Track_Count__c from Song__c])
		{
			System.assertEquals(0, s.Track_Count__c);
		}
	}

	@isTest
	static void testUndelete_changesTrackCountAndGenres()
	{
		Mix__c mix = [select id,Primary_Genre__c, Secondary_Genre__c from Mix__c].get(0);
		List<Song__c> allSongs = [select id, Genre__c, Track_Licences__c,
										(select id From Song__c.Tracks__r) from Song__c];
		List<Track__c> tracks = new List<Track__c>();
		for (Song__c s: allSongs)
		{
			tracks.add(new Track__c(Mix__c = mix.id, Song__c = s.id));
		}
		insert tracks;
		delete tracks;

		Test.startTest();
		undelete tracks;
		Test.stopTest();

		mix = [SELECT Id, Primary_Genre__c, Secondary_Genre__c FROM Mix__c WHERE Id=:mix.Id];
		System.assertEquals('Rock', mix.Primary_Genre__c);
		System.assertEquals('Blues', mix.Secondary_Genre__c);
		for (Song__c s : [SELECT Track_Count__c FROM Song__c])
		{
			System.assertEquals(1, s.Track_Count__c);
		}
	}

	@isTest
	static void testUpdate_changesTrackCountAndGenres()
	{
		Mix__c mix = [select id,Primary_Genre__c, Secondary_Genre__c from Mix__c].get(0);
		List<Song__c> allSongs = [select id, Genre__c, Track_Licences__c,
										(select id From Song__c.Tracks__r) from Song__c];
		List<Track__c> tracks = new List<Track__c>();
		for (Integer i = 0; i < allSongs.get(0).Track_Licences__c; i++)
		{
			tracks.add(new Track__c(Mix__c = mix.Id, Song__c = allSongs.get(0).Id));
		}
		insert tracks;
		Song__c newSong = new Song__c(Name = 'testSong', Genre__c = 'Rock', Track_Licences__c = 21, Track_Count__c = 0,
									Length_m__c = 3.19,	Artist__c = 'BMTH');
		insert newSong;
		tracks.get(0).Song__c = newSong.id;

		Test.startTest();
		update tracks.get(0);
		Test.stopTest();

		mix = [select Id, Primary_Genre__c, Secondary_Genre__c from Mix__c where Id=:mix.Id].get(0);
		newSong = [select Track_Count__c from Song__c where Id=:newSong.Id].get(0);
		System.assertEquals('Blues', mix.Primary_Genre__c);
		System.assertEquals('Rock', mix.Secondary_Genre__c);
		System.assertEquals(1, newSong.Track_Count__c);
	}

	@isTest
	static void testUpdate_checkErrors()
	{
		Mix__c mix = [select id, Primary_Genre__c, Secondary_Genre__c from Mix__c].get(0);
		Song__c song = [select id, Genre__c, Track_Licences__c,
						(select id From Song__c.Tracks__r) from Song__c].get(0);
		List<Track__c> tracks = new List<Track__c>();
		for (Integer i = 0; i < song.Track_Licences__c; i++)
		{
			tracks.add(new Track__c(Mix__c = mix.Id, Song__c = song.Id));
		}
		insert tracks;
		Song__c newSong =
				new Song__c(Name = 'testSong', Genre__c = 'Rock', Track_Licences__c = song.Track_Licences__c,
							Track_Count__c = 0, Length_m__c = 3.19, Artist__c = 'testArt');
		insert newSong;
		for (Track__c t: tracks)
		{
			t.Song__c = newSong.id;
		}

		Test.startTest();
		List<Database.SaveResult> sResult = Database.update(tracks, false);
		Test.stopTest();
		System.assertEquals(false, sResult.get(tracks.size() - 1).isSuccess());
	}

	@isTest
	static void testInsert()
	{
		List<Track__c> trackList = new List<Track__c>();
		List<Song__c> songs = [select id from Song__c];
		List<Mix__c> mixes = [select id from Mix__c];
		for (Song__c s: songs)
		{
			trackList.add(new Track__c(Mix__c = mixes.get(0).id, Song__c = s.id));
		}

		Test.startTest();
		insert trackList;
		Test.stopTest();

		songs = [select Track_Count__c, Genre__c from Song__c];
		Mix__c mix = [select Primary_Genre__c, Secondary_Genre__c from Mix__c where id=: mixes.get(0).id].get(0);
		for (Song__c s: songs)
		{
			System.assertEquals(1, s.Track_Count__c);
		}
		System.assertEquals('Rock', mix.Primary_Genre__c);
		System.assertEquals('Blues', mix.Secondary_Genre__c);
	}

	@isTest static void testInsert_checkErrors()
	{
		List<Track__c> tracks = new List<Track__c>();
		Song__c song = new Song__c(Name = 'testSong', Genre__c = 'Rock', Track_Licences__c = 11, Track_Count__c = 0,
									Length_m__c = 3.19,	Artist__c = 'testArt');
		insert song;
		Mix__c mix = [select id from Mix__c].get(0);

		//amount of tracks is more than amount of licenses
		for (Integer i = 0; i < song.Track_Licences__c; i++)
		{
			tracks.add(new Track__c(Mix__c = mix.id, Song__c = song.id));
		}
		Test.startTest();
		List<Database.SaveResult> sResult = Database.insert(tracks, false);
		Test.stopTest();
		System.assertEquals(false, sResult.get(sResult.size() - 1).isSuccess());
	}
}