objects/Mix__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Genre__c</fullName>
        <label>Primary Genre</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Genre__c</fullName>
        <label>Secondary Genre</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <label>Mix</label>
    <nameField>
        <label>Mix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Song__c.object
<CustomObject>
    <fields>
        <fullName>Genre__c</fullName>
        <label>Genre</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alternative Music</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Blues</fullName>
                </value>
                <value>
                    <fullName>Classical Music</fullName>
                </value>
                <value>
                    <fullName>Country Music</fullName>
                </value>
                <value>
                    <fullName>Dance Music</fullName>
                </value>
                <value>
                    <fullName>Easy Listening</fullName>
                </value>
                <value>
                    <fullName>Hip Hop / Rap</fullName>
                </value>
                <value>
                    <fullName>Indie Pop</fullName>
                </value>
                <value>
                    <fullName>Jazz</fullName>
                </value>
                <value>
                    <fullName>Latin Music</fullName>
                </value>
                <value>
                    <fullName>new Age</fullName>
                </value>
                <value>
                    <fullName>Opera</fullName>
                </value>
                <value>
                    <fullName>Pop (Popular music)</fullName>
                </value>
                <value>
                    <fullName>R&amp;B / Soul</fullName>
                </value>
                <value>
                    <fullName>Reggae</fullName>
                </value>
                <value>
                    <fullName>Rock</fullName>
                </value>
                <value>
                    <fullName>World Music / Beats</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Track_Count__c</fullName>
        <label>Track Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Track__c.object
<CustomObject>
    <fields>
        <fullName>Mix__c</fullName>
        <label>Mix</label>
        <referenceTo>Mix__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Song__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Song</label>
        <referenceTo>Song__c</referenceTo>
        <relationshipLabel>Tracks</relationshipLabel>
        <relationshipName>Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Track</label>
    <nameField>
        <label>Track Autonumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TrackTriggerHandler.cls
/**
 * Created by user on 21.12.2016.
 */
public class TrackTriggerHandler {
	public static void calculateTracks(Set<id> songs) {

		List<Song__c> songList = [
				select Id, Name, Track_Count__c, (select id From Song__c.Tracks__r)
				from Song__c
				where id IN:songs
		];
		for (Song__c song: songList) {
			song.Track_Count__c = song.Tracks__r.size();
		}
		update songList;
	}

	public static void defineGenre(Set<id> mixes, List<Track__c> tracks) {

		List<AggregateResult> groupedResult = [
				select Track__c.Song__r.Genre__c genre, Mix__c mix
				from Track__c
				where Track__c.Mix__c in: mixes
		        group by Mix__c,Track__c.Song__r.Genre__c
		        order by COUNT(Track__c.Song__r.Genre__c) DESC
		];

		List<MIx__c> mixesToUpsert = findMixesToUpsert(groupedResult);

		upsert mixesToUpsert;
	}

	public static List<Mix__c> findMixesToUpsert(List<AggregateResult> groupedResult) {
		Id mId = (Id)groupedResult.get(0).get('mix');
		List<MIx__c> mixesToUpsert = new List<MIx__c>();
		Map<Id, List<String>> mixList = new Map<Id, List<String>>();

		mixList.put(mId, new List<String>());
		mixList.get(mId).add((String)groupedResult.get(0).get('genre'));

		mixesToUpsert.add(new Mix__c(Id = mId, Primary_Genre__c = mixList.get(mId).get(0)));

		for (Integer i = 1; i < groupedResult.size(); i++) {
			mId = (Id)groupedResult.get(i).get('mix');
			if (mixList.containsKey(mId) && mixList.get(mId).size() == 1) {
				mixList.get(mId).add((String)groupedResult.get(i).get('genre'));
				mixesToUpsert.get(mixesToUpsert.size() - 1).Secondary_Genre__c = mixList.get(mId).get(1);
			} else if (!mixList.containsKey(mId)) {
				mixList.put(mId, new List<String>());
				mixList.get(mId).add((String)groupedResult.get(i).get('genre'));
				mixesToUpsert.add(new Mix__c(Id = mId, Primary_Genre__c = mixList.get(mId).get(0)));
			}
		}
		return  mixesToUpsert;
	}
}